apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: platformer
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platformer-admin
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platformer-admin-global
subjects:
- kind: ServiceAccount
  name: platformer
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: platformer-admin
  apiGroup: rbac.authorization.k8s.io